name: detectPendo
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/TestView.swift"
      - "**/Test2View.swift"
      - "**/Test3View.swift"

permissions:
  contents: read
  pull-requests: write

jobs:
  comment-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 300
          ref: ${{ github.head_ref }}
      - id: diff-check
        if: github.event.action == 'synchronize'
        run: |
          diff_files=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=hoge)
          echo "diff-files=$diff_files" >> $GITHUB_OUTPUT
      - id: no-diff-check
        if: github.event.action != 'synchronize'
        run: echo "diff-files=" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        if: steps.diff-check.outputs.diff-files
        with:
          script: |
            const files = steps.diff-check.outputs['diff-files'].split('\n');
            const changedFiles = files.filter(file => file.trim() !== ''); // Remove empty lines
            if (changedFiles.length > 0) {
              const body = `Pendoのファイルが編集されました:\n- ${changedFiles.join('\n- ')}`;
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
            }