name: detectPendo
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  comment-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - id: diff-check
        run: |
          if [[ "${{ github.event.action }}" == "opened" ]]; then
            # 初回のPR作成時はベースブランチとの差分を取得
            base_branch=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
            diff_files=$(git diff $base_branch HEAD --name-only)
          else
            # それ以外の場合はイベントの差分を取得
            diff_files=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only)
          fi
          echo "diff-files=$diff_files" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        if: steps.diff-check.outputs.diff-files != ''
        with:
          script: |
            const diffFiles = '${{ steps.diff-check.outputs['diff-files'] }}';
            const files = diffFiles.split('\n').filter(file => file.trim() !== '');
            const trackedFiles = files.filter(file => 
              file.endsWith('TestView.swift') || 
              file.endsWith('Test2View.swift') || 
              file.endsWith('Test3View.swift')
            );
            
            if (trackedFiles.length > 0) {
              const body = `以下のPendo関連ファイルが編集されました:\n- ${trackedFiles.join('\n- ')}`;
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
            }
