name: detectPendo
on:
  pull_request:
    paths:
      - 'TestView.swift'
      - 'Test2View.swift'

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            TestView.swift
            Test2View.swift

      - name: Create PR comment
        uses: actions/github-script@v7
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const changedFiles = JSON.parse('${{ steps.changed-files.outputs.all_changed_files }}')
            const commentBody = changedFiles.map(file => `Changed file: \`${file}\``).join('\n')
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
